export type SingleBookInfo = {
	id: number;
	user_id: number;
	ISBN: string;
	title: string;
	description: string;
	author_id: number;
	illustrator_id: number;
	print_date: string;
	publisher_id: number;
	original_language: string;
	created_at: string;
	updated_at: string;
	cover: string;
	alt: string;
	author: string;
	illustrator: string;
	publisher: string;
	oName: string;
	website?: string;
	year?: number;
};
